apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeName: worker-ha
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: registry-nfs
              mountPath: /var/lib/registry
      volumes:
        - name: registry-nfs
          nfs:
            server: 192.168.136.130
            path: /home/yossi/project/registry 
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
  selector:
    app: registry
